name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
      - uses: jdx/mise-action@v4
      - name: Format
        run: zig fmt --check build.zig build.zig.zon src
      - name: Tests
        run: zig build test
